name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [macOS-14, ubuntu-24.04]
    name: Test
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - if: ${{ matrix.os == 'macOS-14' }}
        name: Xcode Select Version
        uses: mobiledevops/xcode-select-version-action@v1
        with:
          xcode-select-version: 16.1
      - if: ${{ matrix.os == 'ubuntu-24.04' }}
        name: Install xcbeautify
        run: brew install xcbeautify
      - name: Test
        run: set -o pipefail && swift test | xcbeautify --renderer github-actions
