name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [macOS-14, ubuntu-24.04]
        include:
          - os: macOS-14
            select-xcode-version: true
    name: Test
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - if: ${{ matrix.select-xcode-version }}
        name: Xcode Select Version
        uses: mobiledevops/xcode-select-version-action@v1
        with:
          xcode-select-version: 16.1
      - name: Test
        run: set -o pipefail && swift test | xcbeautify --renderer github-actions
