name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macOS-14
    steps:
      - uses: actions/checkout@v4
      - name: Xcode Select Version
        uses: mobiledevops/xcode-select-version-action@v1
        with:
          xcode-select-version: 15.4
      - name: Test
        run: set -o pipefail && swift test | xcbeautify --renderer github-actions
