name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-macos:
    name: Test on macOS 14
    runs-on: macOS-14
    steps:
      - uses: actions/checkout@v4
      - name: Xcode Select Version
        uses: mobiledevops/xcode-select-version-action@v1
        with:
          xcode-select-version: 16.1
      - name: Test
        run: set -o pipefail && swift test | xcbeautify --renderer github-actions
  test-ubuntu:
    name: Test on Ubuntu 24.04
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install xcbeautify
          set -o pipefail && swift test | xcbeautify --renderer github-actions
  test-windows:
    name: Test on Windows Server 2022
    runs-on: windows-2022
    steps:
      - uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-6.0-release
          tag: 6.0-RELEASE
      - uses: actions/checkout@v4
      - name: Test
        run: |
          Set-StrictMode -Version Latest
          $ErrorActionPreference = "Stop"
          $PSNativeCommandUseErrorActionPreference = $true
          swift test
